config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  get 'dracula', to: 'dracula#index'
  post 'dracula/image', to: 'dracula#image', as: 'image_dracula'

  # Defines the root path route ("/")
  root "dracula#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/dracula_controller.rb
# frozen_string_literal: true

class DraculaController < ApplicationController
  def index; end

  def image
    image_param = params[:image]
    image_file = case image_param
                 when 'novel'
                   'dracula/novel.jpg'
                 when 'castle'
                   'dracula/castle.jpg'
                 else
                   'dracula/novel.jpg' # Default image
                 end

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          'dracula_image',
          partial: 'dracula/image',
          locals: { file: image_file }
        )
      end
      format.html { redirect_to action: :index }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dracula/_image.html.erb
<turbo-frame id="dracula_image">
  <%= render ImageComponent.new(file: local_assigns[:file]) %>
</turbo-frame>

app/views/dracula/index.html.erb
<h1>Hotwire for Ruby on Rails Demo</h1>

<div>
  <p>This is a demo of using Hotwire with a Dracula theme. Click the buttons below to change the image.</p>
</div>

<div>
  <%= render ButtonComponent.new(label: "Dracula Novel", link: image_dracula_path, params: { image: 'novel'}) %>
  <%= render ButtonComponent.new(label: "Dracula Castle", link: image_dracula_path, params: { image: 'castle'}) %>
</div>

<hr>

<div>
  <%= render partial: 'image', locals: { file: 'dracula/novel.jpg' } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Hotwire Rails Dracula Draft" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# Use the Turbe morph page refresh method %>
    <%# https://turbo.hotwired.dev/handbook/page_refreshes %>
    <meta name="turbo-refresh-method" content="morph">

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>